Add distribinstallposthook

diff --git a/scripts/lsstinstall b/scripts/lsstinstall
--- a/scripts/lsstinstall
+++ b/scripts/lsstinstall
@@ -347,6 +347,17 @@ else
     echo "$EUPS_PKGROOT" > "$EUPS_PATH/pkgroot" || fail "Unable to write pkgroot file"
 fi
 
+# Copy postinstall
+callback_folder="$EUPS_PATH/site"
+hook="distribInstallPostHook.py"
+if [ -f "$callback_folder/$hook" ]; then
+    echo "Callback already installed"
+elif [ -n "$dryrun" ]; then
+    $dryrun cat \> $hook
+else
+    callback_url="https://raw.githubusercontent.com/RobertLuptonTheGood/eups/refs/heads/master/callbacks/$hook"
+    cd "$callback_folder" && { run_curl -O "$callback_url"; cd - || fail "Unable to download callback"; }
+fi
 # Create load scripts
 source_cmd=source
 if [ -f loadLSST.sh ]; then
